package constants

var (
	BusinessCategories = []map[string]interface{} {
		{"label": "Advertising/Marketing", "mcc": "7311"},
		{"label": "Amateur Sports Team", "mcc": "7941"},
		{"label": "Architecural Services", "mcc": "8911"},
		{"label": "Appliance Repair Service", "mcc": "7629"},
		{"label": "App Page", "mcc": "5045"},
		{"label": "Architectural Designer", "mcc": "8911"},
		{"label": "Art", "mcc": "5971"},
		{"label": "Arts & Entertainment", "mcc": "5971"},
		{"label": "Automotive Repair Shop", "mcc": "7531"},
		{"label": "Baby & Children’s Clothing Store", "mcc": "5651"},
		{"label": "Bar", "mcc": "5813"},
		{"label": "Beauty, Cosmetic & Personal Care", "mcc": "7230"},
		{"label": "Beauty Salon", "mcc": "7230"},
		{"label": "Book", "mcc": "5942"},
		{"label": "Business Service", "mcc": "7399"},
		{"label": "Camera/Photo", "mcc": "5946"},
		{"label": "Canoe & Kayak Rental", "mcc": "5941"},
		{"label": "Chicken Joint", "mcc": "5812"},
		{"label": "Church of Christ", "mcc": "8661"},
		{"label": "Church of Jesus Christ of Latter-day Saints", "mcc": "8661"},
		{"label": "Clothing (Brand)", "mcc": "5961"},
		{"label": "Clothing Store", "mcc": "5961"},
		{"label": "College & University", "mcc": "8220"},
		{"label": "Commercial & Industrial", "mcc": "5046"},
		{"label": "Commercial & Industrial Equipment Supplier", "mcc": "5046"},
		{"label": "Commercial Bank", "mcc": "6012"},
		{"label": "Commercial Equipment", "mcc": "5046"},
		{"label": "Commercial Real Estate Agency", "mcc": "5613"},
		{"label": "Commercial Truck Dealership", "mcc": "5511"},
		{"label": "Community", "mcc": "1520"},
		{"label": "Community Organization", "mcc": "1520"},
		{"label": "Consulting Agency", "mcc": "7392"},
		{"label": "Contractor", "mcc": "1520"},
		{"label": "Convenience Store", "mcc": "5499"},
		{"label": "Doctor", "mcc": "8011"},
		{"label": "Deli", "mcc": "5812"},
		{"label": "Dancer", "mcc": "7829"},
		{"label": "Design & Fashion", "mcc": "5691"},
		{"label": "Dessert Shop", "mcc": "5812"},
		{"label": "Dorm", "mcc": "6513"},
		{"label": "E-commerce Website", "mcc": "1520"},
		{"label": "Education", "mcc": "8299"},
		{"label": "Engineering Service", "mcc": "1731"},
		{"label": "Entertainment Website", "mcc": "7829"},
		{"label": "Entrepreneur", "mcc": "1520"},
		{"label": "Family Style Restaurant", "mcc": "5812"},
		{"label": "Fashion Designer", "mcc": "5691"},
		{"label": "Fashion Model", "mcc": "5691"},
		{"label": "Fast Food Restaurant", "mcc": "5812"},
		{"label": "Financial Service", "mcc": "6012"},
		{"label": "Food & Beverage", "mcc": "5812"},
		{"label": "Food Stand", "mcc": "5812"},
		{"label": "Footwear Store", "mcc": "5139"},
		{"label": "Gamer", "mcc": "7829"},
		{"label": "Games/Toys", "mcc": "5945"},
		{"label": "Gaming Video Creator", "mcc": "7829"},
		{"label": "Government Organization", "mcc": "9222"},
		{"label": "Graphic Designer", "mcc": "7333"},
		{"label": "Grocery Store", "mcc": "5411"},
		{"label": "Hardware Store", "mcc": "5251"},
		{"label": "Health/Beauty", "mcc": "7298"},
		{"label": "Heating, Ventilating & Air Conditioning Service", "mcc": "7623"},
		{"label": "Home Decor", "mcc": "5712"},
		{"label": "Home Improvement", "mcc": "5712"},
		{"label": "Hospital", "mcc": "8062"},
		{"label": "Hotel", "mcc": "7011"},
		{"label": "Hotel & Lodging", "mcc": "7011"},
		{"label": "Ice Cream Shop", "mcc": "5812"},
		{"label": "In-Home Service", "mcc": "1520"},
		{"label": "Industrial Company", "mcc": "5085"},
		{"label": "Information Technology Company", "mcc": "5734"},
		{"label": "Insurance Company", "mcc": "5960"},
		{"label": "Interior Design Studio", "mcc": "8911"},
		{"label": "Internet Company", "mcc": "5045"},
		{"label": "Internet Marketing Service", "mcc": "5969"},
		{"label": "Japanese Restaurant", "mcc": "5812"},
		{"label": "Jazz & Blues Club", "mcc": "5813"},
		{"label": "Jewelry/Watches", "mcc": "5944"},
		{"label": "Jewelry & Watches Company", "mcc": "5944"},
		{"label": "Journalist", "mcc": "5192"},
		{"label": "Karaoke", "mcc": "5813"},
		{"label": "Kennel", "mcc": "1520"},
		{"label": "Kitchen & Bath Contractor", "mcc": "5712"},
		{"label": "Kitchen/Cooking", "mcc": "5712"},
		{"label": "Korean Restaurant", "mcc": "1582"},
		{"label": "Landmark & Historical Place", "mcc": "7991"},
		{"label": "Lawyer & Law Firm", "mcc": "8111"},
		{"label": "Library", "mcc": "5192"},
		{"label": "Loan Service", "mcc": "6012"},
		{"label": "Local Service", "mcc": "1520"},
		{"label": "Lumber Yard", "mcc": "5211"},
		{"label": "Marketing Agency", "mcc": "5966"},
		{"label": "Media", "mcc": "5815"},
		{"label": "Media/News Company", "mcc": "5192"},
		{"label": "Medical Center", "mcc": "8099"},
		{"label": "Medical School", "mcc": "8099"},
		{"label": "Men’s Clothing Store", "mcc": "5691"},
		{"label": "Mental Health Service", "mcc": "8062"},
		{"label": "Movie", "mcc": "5815"},
		{"label": "Musician/Band", "mcc": "5815"},
		{"label": "Music Lessons & Instruction School", "mcc": "5733"},
		{"label": "Music Video", "mcc": "7829"},
		{"label": "News & Media Website", "mcc": "5192"},
		{"label": "Newspaper", "mcc": "5192"},
		{"label": "Nonprofit Organization", "mcc": "1520"},
		{"label": "Non-Governmental Organization (NGO)", "mcc": "1520"},
		{"label": "Nursing Agency", "mcc": "8050"},
		{"label": "Obstetrician-Gynecologist (OBGYN)", "mcc": "8011"},
		{"label": "Office Equipment Store", "mcc": "5021"},
		{"label": "Office Supplies", "mcc": "5072"},
		{"label": "Optician", "mcc": "8011"},
		{"label": "Optometrist", "mcc": "8011"},
		{"label": "Outdoor & Sporting Goods Company", "mcc": "5941"},
		{"label": "Personal Blog", "mcc": "5815"},
		{"label": "Petting Zoo", "mcc": "7998"},
		{"label": "Photographer", "mcc": "7333"},
		{"label": "Product/Service", "mcc": "1520"},
		{"label": "Public & Government Service", "mcc": "9222"},
		{"label": "Public Utility Company", "mcc": "5225"},
		{"label": "Real Estate", "mcc": "6513"},
		{"label": "Real Estate Agent", "mcc": "6513"},
		{"label": "Real Estate Appraiser", "mcc": "6513"},
		{"label": "Real Estate Company", "mcc": "6513"},
		{"label": "Real Estate Developer", "mcc": "6513"},
		{"label": "Record Label", "mcc": "5735"},
		{"label": "Religious Center", "mcc": "8661"},
		{"label": "Religious Organization", "mcc": "8661"},
		{"label": "Restaurant", "mcc": "5812"},
		{"label": "Retail Bank", "mcc": "5999"},
		{"label": "School", "mcc": "7991"},
		{"label": "Shopping & Retail", "mcc": "7278"},
		{"label": "Shopping District", "mcc": "7278"},
		{"label": "Shopping Mall", "mcc": "7278"},
		{"label": "Smoothie & Juice Bar", "mcc": "5813"},
		{"label": "Specialty School", "mcc": "7911"},
		{"label": "Sports & Recreation", "mcc": "7032"},
		{"label": "Sports League", "mcc": "7941"},
		{"label": "Sports Team", "mcc": "7941"},
		{"label": "Teens & Kids Website", "mcc": "5815"},
		{"label": "Telemarketing Service", "mcc": "5967"},
		{"label": "Tire Dealer & Repair Shop", "mcc": "5532"},
		{"label": "Trade School", "mcc": "8249"},
		{"label": "Traffic School", "mcc": "8249"},
		{"label": "Tutor/Teacher", "mcc": "8299"},
		{"label": "TV Channel", "mcc": "5812"},
		{"label": "TV Network", "mcc": "4899"},
		{"label": "TV Show", "mcc": "4899"},
		{"label": "Udon Restaurant", "mcc": "5812"},
		{"label": "Ukranian Restaurant", "mcc": "5812"},
		{"label": "Unagi Restaurant", "mcc": "5812"},
		{"label": "Uniform Supplier", "mcc": "5137"},
		{"label": "Urban Farm", "mcc": "4225"},
		{"label": "Vacation Home Rental", "mcc": "6513"},
		{"label": "Veterinarian", "mcc": "0742"},
		{"label": "Video Creator", "mcc": "7829"},
		{"label": "Video Game", "mcc": "5816"},
		{"label": "Visual Arts", "mcc": "7333"},
		{"label": "Web Designer", "mcc": "7372"},
		{"label": "Website", "mcc": "5734"},
		{"label": "Wedding Planning Service", "mcc": "8999"},
		{"label": "Winery/Vineyard", "mcc": "5921"},
		{"label": "Women’s Clothing Store", "mcc": "5691"},
		{"label": "Women’s Health Clinic", "mcc": "7289"},
		{"label": "Writer", "mcc": "5999"},
		{"label": "Xinjiang Restaurant", "mcc": "5812"},
		{"label": "Yakiniku Restaurant", "mcc": "5812"},
		{"label": "Yakitori Restaurant", "mcc": "5812"},
		{"label": "Yoga Studio", "mcc": "7298"},
		{"label": "Yoshoku Restaurant", "mcc": "5812"},
		{"label": "Zhejiang Restaurant", "mcc": "5812"},
		{"label": "Zoo", "mcc": "7998"},
}

)